language: go

go:
  - 1.12

before_install:
  # We need Python to run pygmentize for generating HTML.
  - sudo apt-get update
  - sudo apt-get install python

install:
  - go get -u github.com/russross/blackfriday
  - go get -u golang.org/x/text/transform
  - go get -u "golang.org/x/text/unicode/norm"

script:
  - tools/build

env:
  - VERBOSE=1
